//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITStudio
{
    using System;
    using System.Collections.Generic;
    
    public partial class works
    {
        public int id { get; set; }
        public int typeId { get; set; }
        public string title { get; set; }
        public string time { get; set; }
        public string picture { get; set; }
        public string link { get; set; }
        public string introduction { get; set; }
    }
}
