//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITStudio
{
    using System;
    using System.Collections.Generic;
    
    public partial class applications
    {
        public int id { get; set; }
        public string name { get; set; }
        public bool gender { get; set; }
        public string major { get; set; }
        public string tel { get; set; }
        public System.DateTime time { get; set; }
        public string job { get; set; }
        public string introduction { get; set; }
    }
}
