//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITStudio
{
    using System;
    using System.Collections.Generic;
    
    public partial class works
    {
        public works()
        {
            this.workmap = new HashSet<workmap>();
        }
    
        public int id { get; set; }
        public int typeId { get; set; }
        public string title { get; set; }
        public string time { get; set; }
        public string picture { get; set; }
        public string link { get; set; }
        public string introduction { get; set; }
    
        public virtual ICollection<workmap> workmap { get; set; }
    }
}
