//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITStudio
{
    using System;
    using System.Collections.Generic;
    
    public partial class workmap
    {
        public int id { get; set; }
        public int memberId { get; set; }
        public int workId { get; set; }
    
        public virtual members members { get; set; }
        public virtual works works { get; set; }
    }
}
