//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("ITStudioModel", "FK_workmap_members", "members", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ITStudioModel.members), "workmap", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ITStudioModel.workmap), true)]
[assembly: EdmRelationshipAttribute("ITStudioModel", "FK_workmap_works", "works", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ITStudioModel.works), "workmap", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ITStudioModel.workmap), true)]

#endregion

namespace ITStudioModel
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class ITStudioEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“ITStudioEntities”部分中的连接字符串初始化新 ITStudioEntities 对象。
        /// </summary>
        public ITStudioEntities() : base("name=ITStudioEntities", "ITStudioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ITStudioEntities 对象。
        /// </summary>
        public ITStudioEntities(string connectionString) : base(connectionString, "ITStudioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ITStudioEntities 对象。
        /// </summary>
        public ITStudioEntities(EntityConnection connection) : base(connection, "ITStudioEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<admins> admins
        {
            get
            {
                if ((_admins == null))
                {
                    _admins = base.CreateObjectSet<admins>("admins");
                }
                return _admins;
            }
        }
        private ObjectSet<admins> _admins;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<applications> applications
        {
            get
            {
                if ((_applications == null))
                {
                    _applications = base.CreateObjectSet<applications>("applications");
                }
                return _applications;
            }
        }
        private ObjectSet<applications> _applications;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<members> members
        {
            get
            {
                if ((_members == null))
                {
                    _members = base.CreateObjectSet<members>("members");
                }
                return _members;
            }
        }
        private ObjectSet<members> _members;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<notices> notices
        {
            get
            {
                if ((_notices == null))
                {
                    _notices = base.CreateObjectSet<notices>("notices");
                }
                return _notices;
            }
        }
        private ObjectSet<notices> _notices;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<workmap> workmap
        {
            get
            {
                if ((_workmap == null))
                {
                    _workmap = base.CreateObjectSet<workmap>("workmap");
                }
                return _workmap;
            }
        }
        private ObjectSet<workmap> _workmap;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<works> works
        {
            get
            {
                if ((_works == null))
                {
                    _works = base.CreateObjectSet<works>("works");
                }
                return _works;
            }
        }
        private ObjectSet<works> _works;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<workTypes> workTypes
        {
            get
            {
                if ((_workTypes == null))
                {
                    _workTypes = base.CreateObjectSet<workTypes>("workTypes");
                }
                return _workTypes;
            }
        }
        private ObjectSet<workTypes> _workTypes;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<outWorks> outWorks
        {
            get
            {
                if ((_outWorks == null))
                {
                    _outWorks = base.CreateObjectSet<outWorks>("outWorks");
                }
                return _outWorks;
            }
        }
        private ObjectSet<outWorks> _outWorks;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 admins EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToadmins(admins admins)
        {
            base.AddObject("admins", admins);
        }
    
        /// <summary>
        /// 用于向 applications EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToapplications(applications applications)
        {
            base.AddObject("applications", applications);
        }
    
        /// <summary>
        /// 用于向 members EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTomembers(members members)
        {
            base.AddObject("members", members);
        }
    
        /// <summary>
        /// 用于向 notices EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTonotices(notices notices)
        {
            base.AddObject("notices", notices);
        }
    
        /// <summary>
        /// 用于向 workmap EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToworkmap(workmap workmap)
        {
            base.AddObject("workmap", workmap);
        }
    
        /// <summary>
        /// 用于向 works EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToworks(works works)
        {
            base.AddObject("works", works);
        }
    
        /// <summary>
        /// 用于向 workTypes EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToworkTypes(workTypes workTypes)
        {
            base.AddObject("workTypes", workTypes);
        }
    
        /// <summary>
        /// 用于向 outWorks EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTooutWorks(outWorks outWorks)
        {
            base.AddObject("outWorks", outWorks);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITStudioModel", Name="admins")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class admins : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 admins 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="name">name 属性的初始值。</param>
        /// <param name="password">password 属性的初始值。</param>
        public static admins Createadmins(global::System.Int32 id, global::System.String name, global::System.String password)
        {
            admins admins = new admins();
            admins.id = id;
            admins.name = name;
            admins.password = password;
            return admins;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITStudioModel", Name="applications")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class applications : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 applications 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="name">name 属性的初始值。</param>
        /// <param name="gender">gender 属性的初始值。</param>
        /// <param name="major">major 属性的初始值。</param>
        /// <param name="tel">tel 属性的初始值。</param>
        /// <param name="time">time 属性的初始值。</param>
        /// <param name="job">job 属性的初始值。</param>
        public static applications Createapplications(global::System.Int32 id, global::System.String name, global::System.Boolean gender, global::System.String major, global::System.String tel, global::System.DateTime time, global::System.String job)
        {
            applications applications = new applications();
            applications.id = id;
            applications.name = name;
            applications.gender = gender;
            applications.major = major;
            applications.tel = tel;
            applications.time = time;
            applications.job = job;
            return applications;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.Boolean _gender;
        partial void OngenderChanging(global::System.Boolean value);
        partial void OngenderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String major
        {
            get
            {
                return _major;
            }
            set
            {
                OnmajorChanging(value);
                ReportPropertyChanging("major");
                _major = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("major");
                OnmajorChanged();
            }
        }
        private global::System.String _major;
        partial void OnmajorChanging(global::System.String value);
        partial void OnmajorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tel
        {
            get
            {
                return _tel;
            }
            set
            {
                OntelChanging(value);
                ReportPropertyChanging("tel");
                _tel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tel");
                OntelChanged();
            }
        }
        private global::System.String _tel;
        partial void OntelChanging(global::System.String value);
        partial void OntelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime time
        {
            get
            {
                return _time;
            }
            set
            {
                OntimeChanging(value);
                ReportPropertyChanging("time");
                _time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time");
                OntimeChanged();
            }
        }
        private global::System.DateTime _time;
        partial void OntimeChanging(global::System.DateTime value);
        partial void OntimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String job
        {
            get
            {
                return _job;
            }
            set
            {
                OnjobChanging(value);
                ReportPropertyChanging("job");
                _job = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("job");
                OnjobChanged();
            }
        }
        private global::System.String _job;
        partial void OnjobChanging(global::System.String value);
        partial void OnjobChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String introduction
        {
            get
            {
                return _introduction;
            }
            set
            {
                OnintroductionChanging(value);
                ReportPropertyChanging("introduction");
                _introduction = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("introduction");
                OnintroductionChanged();
            }
        }
        private global::System.String _introduction;
        partial void OnintroductionChanging(global::System.String value);
        partial void OnintroductionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITStudioModel", Name="members")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class members : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 members 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="name">name 属性的初始值。</param>
        /// <param name="grade">grade 属性的初始值。</param>
        /// <param name="photo">photo 属性的初始值。</param>
        /// <param name="job">job 属性的初始值。</param>
        /// <param name="direction">direction 属性的初始值。</param>
        /// <param name="introduction">introduction 属性的初始值。</param>
        public static members Createmembers(global::System.Int32 id, global::System.String name, global::System.Int32 grade, global::System.String photo, global::System.String job, global::System.String direction, global::System.String introduction)
        {
            members members = new members();
            members.id = id;
            members.name = name;
            members.grade = grade;
            members.photo = photo;
            members.job = job;
            members.direction = direction;
            members.introduction = introduction;
            return members;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 grade
        {
            get
            {
                return _grade;
            }
            set
            {
                OngradeChanging(value);
                ReportPropertyChanging("grade");
                _grade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("grade");
                OngradeChanged();
            }
        }
        private global::System.Int32 _grade;
        partial void OngradeChanging(global::System.Int32 value);
        partial void OngradeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String photo
        {
            get
            {
                return _photo;
            }
            set
            {
                OnphotoChanging(value);
                ReportPropertyChanging("photo");
                _photo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("photo");
                OnphotoChanged();
            }
        }
        private global::System.String _photo;
        partial void OnphotoChanging(global::System.String value);
        partial void OnphotoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String job
        {
            get
            {
                return _job;
            }
            set
            {
                OnjobChanging(value);
                ReportPropertyChanging("job");
                _job = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("job");
                OnjobChanged();
            }
        }
        private global::System.String _job;
        partial void OnjobChanging(global::System.String value);
        partial void OnjobChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direction
        {
            get
            {
                return _direction;
            }
            set
            {
                OndirectionChanging(value);
                ReportPropertyChanging("direction");
                _direction = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("direction");
                OndirectionChanged();
            }
        }
        private global::System.String _direction;
        partial void OndirectionChanging(global::System.String value);
        partial void OndirectionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String introduction
        {
            get
            {
                return _introduction;
            }
            set
            {
                OnintroductionChanging(value);
                ReportPropertyChanging("introduction");
                _introduction = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("introduction");
                OnintroductionChanged();
            }
        }
        private global::System.String _introduction;
        partial void OnintroductionChanging(global::System.String value);
        partial void OnintroductionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String others
        {
            get
            {
                return _others;
            }
            set
            {
                OnothersChanging(value);
                ReportPropertyChanging("others");
                _others = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("others");
                OnothersChanged();
            }
        }
        private global::System.String _others;
        partial void OnothersChanging(global::System.String value);
        partial void OnothersChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ITStudioModel", "FK_workmap_members", "workmap")]
        public EntityCollection<workmap> workmap
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<workmap>("ITStudioModel.FK_workmap_members", "workmap");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<workmap>("ITStudioModel.FK_workmap_members", "workmap", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITStudioModel", Name="notices")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class notices : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 notices 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="title">title 属性的初始值。</param>
        /// <param name="time">time 属性的初始值。</param>
        /// <param name="content">content 属性的初始值。</param>
        public static notices Createnotices(global::System.Int32 id, global::System.String title, global::System.DateTime time, global::System.String content)
        {
            notices notices = new notices();
            notices.id = id;
            notices.title = title;
            notices.time = time;
            notices.content = content;
            return notices;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime time
        {
            get
            {
                return _time;
            }
            set
            {
                OntimeChanging(value);
                ReportPropertyChanging("time");
                _time = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time");
                OntimeChanged();
            }
        }
        private global::System.DateTime _time;
        partial void OntimeChanging(global::System.DateTime value);
        partial void OntimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String content
        {
            get
            {
                return _content;
            }
            set
            {
                OncontentChanging(value);
                ReportPropertyChanging("content");
                _content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("content");
                OncontentChanged();
            }
        }
        private global::System.String _content;
        partial void OncontentChanging(global::System.String value);
        partial void OncontentChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITStudioModel", Name="outWorks")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class outWorks : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 outWorks 对象。
        /// </summary>
        /// <param name="memberId">memberId 属性的初始值。</param>
        /// <param name="workId">workId 属性的初始值。</param>
        /// <param name="picture">picture 属性的初始值。</param>
        /// <param name="time">time 属性的初始值。</param>
        /// <param name="title">title 属性的初始值。</param>
        /// <param name="introduction">introduction 属性的初始值。</param>
        public static outWorks CreateoutWorks(global::System.Int32 memberId, global::System.Int32 workId, global::System.String picture, global::System.String time, global::System.String title, global::System.String introduction)
        {
            outWorks outWorks = new outWorks();
            outWorks.memberId = memberId;
            outWorks.workId = workId;
            outWorks.picture = picture;
            outWorks.time = time;
            outWorks.title = title;
            outWorks.introduction = introduction;
            return outWorks;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 memberId
        {
            get
            {
                return _memberId;
            }
            set
            {
                if (_memberId != value)
                {
                    OnmemberIdChanging(value);
                    ReportPropertyChanging("memberId");
                    _memberId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("memberId");
                    OnmemberIdChanged();
                }
            }
        }
        private global::System.Int32 _memberId;
        partial void OnmemberIdChanging(global::System.Int32 value);
        partial void OnmemberIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 workId
        {
            get
            {
                return _workId;
            }
            set
            {
                if (_workId != value)
                {
                    OnworkIdChanging(value);
                    ReportPropertyChanging("workId");
                    _workId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("workId");
                    OnworkIdChanged();
                }
            }
        }
        private global::System.Int32 _workId;
        partial void OnworkIdChanging(global::System.Int32 value);
        partial void OnworkIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String picture
        {
            get
            {
                return _picture;
            }
            set
            {
                if (_picture != value)
                {
                    OnpictureChanging(value);
                    ReportPropertyChanging("picture");
                    _picture = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("picture");
                    OnpictureChanged();
                }
            }
        }
        private global::System.String _picture;
        partial void OnpictureChanging(global::System.String value);
        partial void OnpictureChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String time
        {
            get
            {
                return _time;
            }
            set
            {
                if (_time != value)
                {
                    OntimeChanging(value);
                    ReportPropertyChanging("time");
                    _time = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("time");
                    OntimeChanged();
                }
            }
        }
        private global::System.String _time;
        partial void OntimeChanging(global::System.String value);
        partial void OntimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                if (_title != value)
                {
                    OntitleChanging(value);
                    ReportPropertyChanging("title");
                    _title = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("title");
                    OntitleChanged();
                }
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String introduction
        {
            get
            {
                return _introduction;
            }
            set
            {
                if (_introduction != value)
                {
                    OnintroductionChanging(value);
                    ReportPropertyChanging("introduction");
                    _introduction = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("introduction");
                    OnintroductionChanged();
                }
            }
        }
        private global::System.String _introduction;
        partial void OnintroductionChanging(global::System.String value);
        partial void OnintroductionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITStudioModel", Name="workmap")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class workmap : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 workmap 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="memberId">memberId 属性的初始值。</param>
        /// <param name="workId">workId 属性的初始值。</param>
        public static workmap Createworkmap(global::System.Int32 id, global::System.Int32 memberId, global::System.Int32 workId)
        {
            workmap workmap = new workmap();
            workmap.id = id;
            workmap.memberId = memberId;
            workmap.workId = workId;
            return workmap;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 memberId
        {
            get
            {
                return _memberId;
            }
            set
            {
                OnmemberIdChanging(value);
                ReportPropertyChanging("memberId");
                _memberId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("memberId");
                OnmemberIdChanged();
            }
        }
        private global::System.Int32 _memberId;
        partial void OnmemberIdChanging(global::System.Int32 value);
        partial void OnmemberIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 workId
        {
            get
            {
                return _workId;
            }
            set
            {
                OnworkIdChanging(value);
                ReportPropertyChanging("workId");
                _workId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("workId");
                OnworkIdChanged();
            }
        }
        private global::System.Int32 _workId;
        partial void OnworkIdChanging(global::System.Int32 value);
        partial void OnworkIdChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ITStudioModel", "FK_workmap_members", "members")]
        public members members
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<members>("ITStudioModel.FK_workmap_members", "members").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<members>("ITStudioModel.FK_workmap_members", "members").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<members> membersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<members>("ITStudioModel.FK_workmap_members", "members");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<members>("ITStudioModel.FK_workmap_members", "members", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ITStudioModel", "FK_workmap_works", "works")]
        public works works
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<works>("ITStudioModel.FK_workmap_works", "works").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<works>("ITStudioModel.FK_workmap_works", "works").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<works> worksReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<works>("ITStudioModel.FK_workmap_works", "works");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<works>("ITStudioModel.FK_workmap_works", "works", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITStudioModel", Name="works")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class works : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 works 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="typeId">typeId 属性的初始值。</param>
        /// <param name="title">title 属性的初始值。</param>
        /// <param name="time">time 属性的初始值。</param>
        /// <param name="picture">picture 属性的初始值。</param>
        /// <param name="introduction">introduction 属性的初始值。</param>
        public static works Createworks(global::System.Int32 id, global::System.Int32 typeId, global::System.String title, global::System.String time, global::System.String picture, global::System.String introduction)
        {
            works works = new works();
            works.id = id;
            works.typeId = typeId;
            works.title = title;
            works.time = time;
            works.picture = picture;
            works.introduction = introduction;
            return works;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 typeId
        {
            get
            {
                return _typeId;
            }
            set
            {
                OntypeIdChanging(value);
                ReportPropertyChanging("typeId");
                _typeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("typeId");
                OntypeIdChanged();
            }
        }
        private global::System.Int32 _typeId;
        partial void OntypeIdChanging(global::System.Int32 value);
        partial void OntypeIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String time
        {
            get
            {
                return _time;
            }
            set
            {
                OntimeChanging(value);
                ReportPropertyChanging("time");
                _time = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("time");
                OntimeChanged();
            }
        }
        private global::System.String _time;
        partial void OntimeChanging(global::System.String value);
        partial void OntimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String picture
        {
            get
            {
                return _picture;
            }
            set
            {
                OnpictureChanging(value);
                ReportPropertyChanging("picture");
                _picture = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("picture");
                OnpictureChanged();
            }
        }
        private global::System.String _picture;
        partial void OnpictureChanging(global::System.String value);
        partial void OnpictureChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String link
        {
            get
            {
                return _link;
            }
            set
            {
                OnlinkChanging(value);
                ReportPropertyChanging("link");
                _link = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("link");
                OnlinkChanged();
            }
        }
        private global::System.String _link;
        partial void OnlinkChanging(global::System.String value);
        partial void OnlinkChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String introduction
        {
            get
            {
                return _introduction;
            }
            set
            {
                OnintroductionChanging(value);
                ReportPropertyChanging("introduction");
                _introduction = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("introduction");
                OnintroductionChanged();
            }
        }
        private global::System.String _introduction;
        partial void OnintroductionChanging(global::System.String value);
        partial void OnintroductionChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ITStudioModel", "FK_workmap_works", "workmap")]
        public EntityCollection<workmap> workmap
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<workmap>("ITStudioModel.FK_workmap_works", "workmap");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<workmap>("ITStudioModel.FK_workmap_works", "workmap", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ITStudioModel", Name="workTypes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class workTypes : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 workTypes 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        /// <param name="name">name 属性的初始值。</param>
        public static workTypes CreateworkTypes(global::System.Int32 id, global::System.String name)
        {
            workTypes workTypes = new workTypes();
            workTypes.id = id;
            workTypes.name = name;
            return workTypes;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
    }

    #endregion

    
}
